// pages/index.tsx

import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { AppBar, Toolbar, Typography, Button } from "@mui/material";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  const router = useRouter();

  const handleLogin = () => {
    setIsAuthenticated(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="static">
        <Toolbar>
          <Image src="/logo.png" alt="Logo" width={40} height={40} />
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            Your Website Name
          </Typography>
          <Button color="inherit">Home</Button>
          <Button color="inherit">About</Button>
          <Button color="inherit">Contact</Button>
          <Button
            color="inherit"
            onClick={() => {
              router.push("/loginform");
            }}
          >
            Login
          </Button>
        </Toolbar>
      </AppBar>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js on Replit!</h1>

        {/* Content of the main section */}
      </main>
    </div>
  );
};

export default Home;
